services:

  migrate:
    container_name: job-scraper-migrate
    build:
      context: .
    command: alembic upgrade head
    env_file: .env
    restart: "no"
    network_mode: host

  celery-worker:
    container_name: job-scraper-worker
    build:
      context: .
    command: celery -A celery_app.config worker --loglevel=info -Q main,scraping -c 5
    env_file: .env
    restart: always
    network_mode: host

  celery-beat:
    container_name: job-scraper-beat
    build:
      context: .
    command: celery -A celery_app.config beat --loglevel=info
    env_file: .env
    restart: unless-stopped
    network_mode: host
