"""composite_unique_url_published_at

Revision ID: 2a9aecc5c88c
Revises: 9f3d2e1a0b4c
Create Date: 2026-04-11 14:04:51.327238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9aecc5c88c'
down_revision: Union[str, None] = '9f3d2e1a0b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_url_key', 'jobs', type_='unique')
    op.create_unique_constraint('uq_jobs_url_published_at', 'jobs', ['url', 'published_at'])
    op.create_unique_constraint(None, 'jobs', ['id'])
    op.create_unique_constraint(None, 'raw_responses', ['id'])
    op.create_unique_constraint(None, 'scraping_sessions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scraping_sessions', type_='unique')
    op.drop_constraint(None, 'raw_responses', type_='unique')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_constraint('uq_jobs_url_published_at', 'jobs', type_='unique')
    op.create_unique_constraint('jobs_url_key', 'jobs', ['url'])
    # ### end Alembic commands ###
