"""init

Revision ID: 8c15434d440a
Revises: 2f1506aa46c7
Create Date: 2026-02-13 09:24:48.023920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c15434d440a'
down_revision: Union[str, None] = '2f1506aa46c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sites', ['id'])
    op.add_column('works', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('works', sa.Column('salary', sa.Text(), nullable=True))
    op.add_column('works', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('works', sa.Column('company', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'works', ['id'])
    op.create_unique_constraint(None, 'works', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='unique')
    op.drop_constraint(None, 'works', type_='unique')
    op.drop_column('works', 'company')
    op.drop_column('works', 'city')
    op.drop_column('works', 'salary')
    op.drop_column('works', 'description')
    op.drop_constraint(None, 'sites', type_='unique')
    # ### end Alembic commands ###
